image: node:20-alpine

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - cp src/assets/uber-icon.png public/uber-icon.png
pages:
    path_prefix: "uber" 
artifacts:
    paths:
      - public
only:
    - main
