image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir -p public/root/uber
    - cp -r dist/* public/root/uber/
    - ls -la public/root/uber/ # для отладки
  artifacts:
    paths:
      - public
  only:
    - main
